version: '3.9'

services:
  obelix-quarry-impl:
    build:
      context: ./backend/obelix-quarry-impl
    ports:
      - "8081:8080"
    networks:
      - backend-network

  obelix-basket-impl:
    build:
      context: ./backend/obelix-basket-impl
    ports:
      - "8082:8080"
    depends_on:
      - obelix-quarry-impl
    networks:
      - backend-network

  obelix-webshop:
    build:
      context: ./backend/obelix-webshop
    ports:
      - "8080:8080"
    depends_on:
      - obelix-basket-impl
      - obelix-quarry-impl
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge