version: '3.9'

services:
  obelix-common:
    build:
      context: ./obelix-common
    ports:
      - "8090:8080"
    networks:
      - backend-network

  obelix-quarry-api:
    build:
      context: ./obelix-quarry-impl
    ports:
      - "8081:8080"
    depends_on:
      - obelix-common
    networks:
      - backend-network

  obelix-basket-api:
    build:
      context: ./obelix-basket-impl
    ports:
      - "8082:8080"
    depends_on:
      - obelix-common
    networks:
      - backend-network

  obelix-webshop:
    build:
      context: ./obelix-webshop
    ports:
      - "8080:8080"
    depends_on:
      - obelix-basket-api
      - obelix-quarry-api
      - obelix-common
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge