version: "3.9"

services:
  webshop:
    build: ./backend/obelix-webshop
    ports:
      - "8080:8080"

  quarry:
    build: ./backend/obelix-quarry-impl
    ports:
      - "8081:8081"

  basket:
    build: ./backend/obelix-basket-impl
    ports:
      - "8082:8082"

networks:
  default:
    driver: bridge