name: 'Backend: Build & Push Images to GHCR'

on:
  workflow_run:
    workflows: ['Backend: Tests']
    types: [completed]
    branches:
      - 'main'



jobs:
  backend-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service:
          - obelix-webshop
          - obelix-quarry-impl
          - obelix-basket-impl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & Push
      - name: Build & Push Backend Service
        uses: docker/build-push-action@v5
        with:
          context: backend
          dockerfile: backend/${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:${{ github.sha }}